apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv2
  namespace: demo  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srv2
  template:
    metadata:
      labels:
        app: srv2
        version: v2.0 
    spec:
      containers:
      - name: srv2
        image: public.ecr.aws/t1x4x6v9/demo:v2.0 #demo:v1.0 -v5.0 each has a specific url path 
        ports: 
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: srv2
  namespace: demo  
spec:
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: srv2
