apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv1
  namespace: production  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: srv1
  template:
    metadata:
      labels:
        app: srv1
    spec:
      containers:
      - name: srv1
        image: public.ecr.aws/t1x4x6v9/demo:v1.0
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: srv1
  namespace: production  
spec:
  ports:
  - port: 80
    targetPort: 5001
    name: http
  selector:
    app: srv1
