---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: demo-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: demo-cluster-issuer
    solvers:
      - selector: {}
        http01:
          ingress:
            class: apisix