---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apisix.rachakondadharmendra.info
  namespace: ingress-apisix
spec:
  secretName: apisix-sercet-com-crt
  dnsNames:
    - apisix.rachakondadharmendra.info
  issuerRef:
    name: demo-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io